module.exports = [
  'Afrikaans',
  'Azərbaycan dili (Latın)',
  'Bahasa Indonesia',
  'Bahasa Melayu',
  'Bosanski (Latinica)',
  'Català',
  'Čeština',
  'Cymraeg',
  'Dansk',
  'Deutsch',
  'Eesti',
  'English (United Kingdom)',
  'English (United States)',
  'Español',
  'Euskara',
  'Filipino',
  'Français',
  'Gaeilge',
  'Gàidhlig',
  'Galego',
  'Hausa',
  'Hrvatski',
  'Igbo',
  'isiXhosa',
  'isiZulu',
  'Íslenska',
  'Italiano',
  'K\'iche\'',
  'Kinyarwanda',
  'Kiswahili',
  'Latviešu',
  'Lëtzebuergesch',
  'Lietuvių',
  'Magyar',
  'Malti',
  'Māori',
  'Nederlands',
  'Norsk (Bokmål)',
  'Norsk (Nynorsk)',
  'O‘zbekcha (Lotin)',
  'Polski',
  'Português (Brasil)',
  'Português (Portugal)',
  'Quechua',
  'Română',
  'Sesotho sa Leboa',
  'Setswana',
  'Shqip',
  'Slovenčina',
  'Slovenščina',
  'Srpski (Srbija, Crna Gora)',
  'Suomi',
  'Svenska',
  'Tiếng Việt',
  'Türkçe',
  'Türkmençe',
  'Valencià',
  'Wolof',
  'Yorùbá',
  'Ελληνικά',
  'Беларускі',
  'български',
  'Кыргызча', 'Қазақ',
  'Македонски',
  'Монгол (Кирилл)',
  'Русский',
  'српски (Босна и Херцеговина)',
  'српски (Србија, Црна Гора)',
  'Татарча',
  'Тоҷикӣ',
  'Українська',
  'Հայերեն',
  'ქართული',
  'עברית',
  'اردو',
  'اللغة العربية',
  'پنجابی',
  'درى',
  'سنڌي',
  'فارسی',
  'کوردیی ناوەڕاست',
  'ئۇيغۇرچە',
  'कोंकणी',
  'नेपाली',
  'मराठी',
  'हिंदी',
  'অসমীয়া',
  'বাংলা (বাংলাদেশ)',
  'বাংলা (ভারত)',
  'ਪੰਜਾਬੀ (ਗੁਰਮੁਖੀ)',
  ' ગુજરાતી',
  'ଓଡ଼ିଆ',
  'தமிழ்',
  'తెలుగు',
  'ಕನ್ನಡ ',
  'മലയാളം',
  'සිංහල',
  'ไทย',
  'ខ្មែរ',
  'ᏣᎳᎩ',
  'ትግርኛ',
  'አማርኛ',
  '한국어',
  '日本語',
  '简体中文',
  '繁體中文'
];
